export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';
export const CITY_SELECTED_SUCCESS = 'CITY_SELECTED_SUCCESS';
export const GET_LOCAL_CITY_SUCCESS = 'GET_LOCAL_CITY_SUCCESS'; 
